"""
tests/test_profile_updater.py
──────────────────────────────
Unit tests for memory_vault/profile_updater.py (GAP 5).

Tests cover:
  - Skips when wiki file is missing
  - Skips when wiki file is an empty stub (too small)
  - Skips when wiki hasn't changed since last update (cache hit)
  - Correctly extracts a compact summary from wiki content
  - Correctly replaces the USER PROFILE section in JARVIS_CORE.md
  - Correctly replaces content even when profile has existing distilled data
  - Force=True bypasses the cache check
  - Gracefully handles missing JARVIS_CORE.md
  - Does not overwrite the OPERATING RULES section below USER PROFILE
"""

import json
import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock


# ── Fixtures ───────────────────────────────────────────────────────────────────

STUB_WIKI = """---
# JARVIS User Profile Wiki
# Auto-generated by nightly distillation job. Human-editable.
# Last updated: [auto-filled by distiller]
---
"""

DISTILLED_WIKI = """---
# JARVIS User Profile Wiki
# Auto-generated by nightly distillation job. Human-editable.
# Last updated: 2026-04-20 02:00 UTC
---

## Summary
User is Hitansu Parichha, a software engineer at Nisum Technologies working on
Project J.A.R.V.I.S. and planning a startup in 2026.

## Technology Preferences
- Prefers TypeScript over plain JavaScript
- Uses Zustand for React state management (replaced Redux)
- Deploys on AWS EC2 with PM2

## Work Patterns
- Most productive 10pm–1am IST
- Clean architecture preferred
- camelCase variable naming
"""

JARVIS_CORE_TEMPLATE = """# J.A.R.V.I.S. — CORE IDENTITY FILE v5.2

## IDENTITY
You are JARVIS.

---

## USER PROFILE
# This section is automatically maintained by the nightly distillation job.

  Name           : Hitansu Parichha
  Employer       : Nisum Technologies
  Role           : Software Engineer
  Primary OS     : macOS (M4 Pro)

---

## OPERATING RULES

- API keys: Never log, speak, or write to memory.

---
"""


# ── Import helper ──────────────────────────────────────────────────────────────

def get_updater_module():
    from memory_vault import profile_updater
    return profile_updater


# ── Tests: skip conditions ─────────────────────────────────────────────────────

class TestProfileUpdaterSkipConditions:

    def test_imports(self):
        from memory_vault.profile_updater import update_jarvis_core_profile
        assert callable(update_jarvis_core_profile)

    def test_skips_when_wiki_missing(self, tmp_path):
        mod = get_updater_module()
        with patch.object(mod, "USER_PROFILE_WIKI", tmp_path / "nonexistent.md"):
            result = mod.update_jarvis_core_profile()
        assert result is False

    def test_skips_when_wiki_is_stub(self, tmp_path):
        mod = get_updater_module()
        stub_file = tmp_path / "user_profile.md"
        stub_file.write_text(STUB_WIKI, encoding="utf-8")
        with patch.object(mod, "USER_PROFILE_WIKI", stub_file):
            result = mod.update_jarvis_core_profile()
        assert result is False

    def test_skips_when_cache_matches(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        # Pre-fill cache with the correct hash
        hash_val = mod._hash_text(DISTILLED_WIKI.strip())
        cache_file = tmp_path / "user_profile_cache.json"
        cache_file.write_text(json.dumps({"wiki_hash": hash_val}))

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            result = mod.update_jarvis_core_profile(force=False)
        assert result is False

    def test_force_bypasses_cache(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        core_file = tmp_path / "JARVIS_CORE.md"
        core_file.write_text(JARVIS_CORE_TEMPLATE, encoding="utf-8")

        cache_file = tmp_path / "cache.json"
        hash_val = mod._hash_text(DISTILLED_WIKI.strip())
        cache_file.write_text(json.dumps({"wiki_hash": hash_val}))

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", core_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            result = mod.update_jarvis_core_profile(force=True)
        assert result is True

    def test_skips_when_jarvis_core_missing(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        missing_core = tmp_path / "nonexistent_JARVIS_CORE.md"

        cache_file = tmp_path / "cache.json"
        cache_file.write_text(json.dumps({}))

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", missing_core),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            result = mod.update_jarvis_core_profile()
        assert result is False


# ── Tests: summary extraction ──────────────────────────────────────────────────

class TestExtractCompactSummary:

    def test_extracts_non_empty_summary(self):
        mod = get_updater_module()
        result = mod._extract_compact_summary(DISTILLED_WIKI)
        assert result
        assert len(result.strip()) > 0

    def test_strips_yaml_header(self):
        mod = get_updater_module()
        result = mod._extract_compact_summary(DISTILLED_WIKI)
        assert "auto-generated" not in result.lower()
        assert "last updated" not in result.lower()

    def test_strips_jarvis_wiki_header_lines(self):
        mod = get_updater_module()
        result = mod._extract_compact_summary(DISTILLED_WIKI)
        assert "JARVIS User Profile Wiki" not in result

    def test_respects_max_lines(self):
        mod = get_updater_module()
        long_wiki = DISTILLED_WIKI + "\n".join(f"- Extra fact {i}" for i in range(50))
        result = mod._extract_compact_summary(long_wiki, max_lines=5)
        lines = [l for l in result.splitlines() if l.strip()]
        assert len(lines) <= 6  # 5 + overflow indicator

    def test_includes_overflow_indicator_when_truncated(self):
        mod = get_updater_module()
        long_wiki = DISTILLED_WIKI + "\n".join(f"- Extra fact {i}" for i in range(50))
        result = mod._extract_compact_summary(long_wiki, max_lines=5)
        assert "wiki/user_profile.md" in result

    def test_returns_empty_for_stub_content(self):
        mod = get_updater_module()
        result = mod._extract_compact_summary(STUB_WIKI)
        assert result == ""


# ── Tests: JARVIS_CORE.md section replacement ──────────────────────────────────

class TestReplaceProfileSection:

    def test_replaces_user_profile_section(self):
        mod = get_updater_module()
        new_summary = "  Name: Hitansu\n  Employer: Nisum"
        result = mod._replace_profile_section(JARVIS_CORE_TEMPLATE, new_summary)
        assert result is not None
        assert "Name: Hitansu" in result

    def test_returns_none_when_section_missing(self):
        mod = get_updater_module()
        content_without_profile = "# JARVIS\n\n## IDENTITY\nYou are JARVIS.\n\n---\n"
        result = mod._replace_profile_section(content_without_profile, "some summary")
        assert result is None

    def test_preserves_operating_rules_section(self):
        mod = get_updater_module()
        new_summary = "  Name: Hitansu"
        result = mod._replace_profile_section(JARVIS_CORE_TEMPLATE, new_summary)
        assert result is not None
        assert "OPERATING RULES" in result
        assert "API keys: Never log" in result

    def test_preserves_identity_section(self):
        mod = get_updater_module()
        new_summary = "  Name: Hitansu"
        result = mod._replace_profile_section(JARVIS_CORE_TEMPLATE, new_summary)
        assert result is not None
        assert "You are JARVIS" in result

    def test_adds_timestamp_comment(self):
        mod = get_updater_module()
        new_summary = "  Name: Hitansu"
        result = mod._replace_profile_section(JARVIS_CORE_TEMPLATE, new_summary)
        assert result is not None
        assert "Auto-updated" in result or "auto-updated" in result.lower()


# ── Tests: full end-to-end update ─────────────────────────────────────────────

class TestFullProfileUpdate:

    def test_full_update_succeeds(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        core_file = tmp_path / "JARVIS_CORE.md"
        core_file.write_text(JARVIS_CORE_TEMPLATE, encoding="utf-8")

        cache_file = tmp_path / "cache.json"
        cache_file.write_text("{}")

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", core_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            result = mod.update_jarvis_core_profile()

        assert result is True

    def test_updated_core_contains_distilled_facts(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        core_file = tmp_path / "JARVIS_CORE.md"
        core_file.write_text(JARVIS_CORE_TEMPLATE, encoding="utf-8")

        cache_file = tmp_path / "cache.json"
        cache_file.write_text("{}")

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", core_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            mod.update_jarvis_core_profile()

        updated = core_file.read_text(encoding="utf-8")
        # Wiki content (e.g. "TypeScript" or "Zustand") should appear
        assert "TypeScript" in updated or "Zustand" in updated or "Nisum" in updated

    def test_cache_written_after_update(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        core_file = tmp_path / "JARVIS_CORE.md"
        core_file.write_text(JARVIS_CORE_TEMPLATE, encoding="utf-8")

        cache_file = tmp_path / "cache.json"
        cache_file.write_text("{}")

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", core_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            mod.update_jarvis_core_profile()

        cache = json.loads(cache_file.read_text())
        assert "wiki_hash" in cache
        assert "last_updated" in cache

    def test_second_run_is_no_op_without_force(self, tmp_path):
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        core_file = tmp_path / "JARVIS_CORE.md"
        core_file.write_text(JARVIS_CORE_TEMPLATE, encoding="utf-8")

        cache_file = tmp_path / "cache.json"
        cache_file.write_text("{}")

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", core_file),
            patch.object(mod, "PROFILE_CACHE_PATH", cache_file),
        ):
            first = mod.update_jarvis_core_profile()
            second = mod.update_jarvis_core_profile()

        assert first is True
        assert second is False  # Cache hit — no redundant write

    def test_graceful_on_exception(self, tmp_path):
        """profile_updater must never raise — it is called in gateway startup."""
        mod = get_updater_module()

        wiki_file = tmp_path / "user_profile.md"
        wiki_file.write_text(DISTILLED_WIKI, encoding="utf-8")

        with (
            patch.object(mod, "USER_PROFILE_WIKI", wiki_file),
            patch.object(mod, "JARVIS_CORE_PATH", Path("/nonexistent/JARVIS_CORE.md")),
            patch.object(mod, "PROFILE_CACHE_PATH", tmp_path / "cache.json"),
        ):
            # Should return False (skip), not raise
            result = mod.update_jarvis_core_profile()
        assert result is False
